config/routes.rb
SampleApplication::Application.routes.draw do

  # Setup the REST URIs for users
  resources :users do
    member do
      # pages for viewing user followers and users they follow
      get :following, :followers
    end
  end

  # Setup the REST URIs for sessions. The only restricts
  # the REST to only new, create and destroy leaving
  # edit out as it is not needed.
  resources :sessions, only: [:new, :create, :destroy]

  # Setup the REST UIRs for microposts but only for
  # create and destroy.  
  resources :microposts, only: [:create, :destroy]

  # Creates a create and destroy route for relationships
  resources :relationships, only: [:create, :destroy]

  # Routes /home to the static_pages action
  # home. This loads the home.html.erb page.
  # It also creates two names routes, home_path
  # and home_url.
  root to: 'static_pages#home'

  # Routes /help to the static_pages action
  # help. This loads the help.html.erb page.
  # It also creates two names routes, help_path
  # and help_url.
  match '/help', to: 'static_pages#help'

  # Routes /about to the static_pages action
  # about. This loads the about.html.erb page.
  # It also creates two names routes, about_path
  # and about_url.
   match '/about', to: 'static_pages#about'

  # Routes /contact to the static_pages action
  # contact. This loads the contact.html.erb page.
  # It also creates two names routes, contact_path
  # and contact_url.
   match '/contact', to: 'static_pages#contact'

  # Routes /signup to the new action
  # in users. This loads the new.html.erb page.
  # It also creates two names routes, signup_path
  # and signup_url.
   match '/signup', to: 'users#new'

  # Routes /signup to the new action in the sessions
  # controller.
   match '/signin', to: 'sessions#new'

  # Routes /signout to the destroy action in the sessions
  # controller. The via: :delete indicates that the DELETE
  # HTTP request should be used for this. 
   match '/signout', to: 'sessions#destroy', via: :delete
end

app/views/shared/_error_messages.html.erb
<% # Check for any errors in the object passed in. If so,
   # execute the code within.
%>
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      <% # Counts the number of errors there is and using the
         # pluralize method adds error for one and errors for
         # greater than one.
      %>
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <%
      # Cycle through the array of errors by listing
      # each full_message and sending it into the block
      # as the msg block variable.
    %>
    <% object.errors.full_messages.each do |msg| %>
      <% # Create a list item for each error message %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% # Check to see if there is any feed items %>
<% if @feed_items.any? %>
  <ol class="microposts">
    <% # Render the feed_item partial passing in the collection @feed_items %>
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>

  <% # Break micropost into multi-page layout %>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<% # Create li with id of feed_item %>
<li id="<%= feed_item.id %>">
  
  <% # Create gravatat for user that belongs to micropost %>
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    
    <% # Create a link to user that blongs to micropost %>
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>

  <% # Create span containing the content of the micropost %>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">

  	<% # Create span with time since post was created %>
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>

  <% # If owner of micropost add delete option %>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<% 
	# Create a form with micropost object and assign form to block
	# variable f
%>
<%= form_for(@micropost) do |f| %>
  <% # Render error_messages partial sending it hash with object of f %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<% # Add text area to form and place placeholder %>
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <% # Add a submit button to the form with method of POST %>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<%
  # Displays the number of following and followed for user and gives
  # them a link to the following and followed pages.
%>
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>