config/routes.rb
SampleApplication::Application.routes.draw do

  # Setup the REST URIs for users
  resources :users do
    member do
      # pages for viewing user followers and users they follow
      get :following, :followers
    end
  end

  # Setup the REST URIs for sessions. The only restricts
  # the REST to only new, create and destroy leaving
  # edit out as it is not needed.
  resources :sessions, only: [:new, :create, :destroy]

  # Setup the REST UIRs for microposts but only for
  # create and destroy.  
  resources :microposts, only: [:create, :destroy]

  # Creates a create and destroy route for relationships
  resources :relationships, only: [:create, :destroy]

  # Routes /home to the static_pages action
  # home. This loads the home.html.erb page.
  # It also creates two names routes, home_path
  # and home_url.
  root to: 'static_pages#home'

  # Routes /help to the static_pages action
  # help. This loads the help.html.erb page.
  # It also creates two names routes, help_path
  # and help_url.
  match '/help', to: 'static_pages#help'

  # Routes /about to the static_pages action
  # about. This loads the about.html.erb page.
  # It also creates two names routes, about_path
  # and about_url.
   match '/about', to: 'static_pages#about'

  # Routes /contact to the static_pages action
  # contact. This loads the contact.html.erb page.
  # It also creates two names routes, contact_path
  # and contact_url.
   match '/contact', to: 'static_pages#contact'

  # Routes /signup to the new action
  # in users. This loads the new.html.erb page.
  # It also creates two names routes, signup_path
  # and signup_url.
   match '/signup', to: 'users#new'

  # Routes /signup to the new action in the sessions
  # controller.
   match '/signin', to: 'sessions#new'

  # Routes /signout to the destroy action in the sessions
  # controller. The via: :delete indicates that the DELETE
  # HTTP request should be used for this. 
   match '/signout', to: 'sessions#destroy', via: :delete
end

app/views/layouts/_footer.html.erb
<!-- Footer of the page -->
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <!-- Navigation bar for the footer. -->
  <nav>
    <ul>
      <%
        # Create a hyperlink with text About and a
        # blank href using the # synbol.
      %>
      <li><%= link_to "About", about_path %></li>
      
      <%
        # Create a hyperlink with text About and a
        # blank href using the # synbol.
      %>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- 
	Classes used in layout have specific meaning in Bootstrap
	Bootstrap it a gemfile supplied by twitter for generating
	CSS easily and quick formatting of page latout. 
-->

<!-- Top of page -->
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <% 
      	# Logo at top of page.
      	# link_to creates a html hyperlink with the text
      	# sample app being visible. Currently the href will
      	# link to # and it will have an id of logo.
      %>
      <%= link_to "sample app", root_path, id: "logo" %>
      <!-- navigation bar for the site -->
      <nav>
        <ul class="nav pull-right">
          <%
          	# link_to is used to create hyperlinks for the
          	# navigation bar. The first parameter is the text
          	# that will be displayed such as Home. The next
          	# parameter is were the href will direct the browser.
          	# At this point it is using the # sysmbol for a blank
          	# link.
          %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          
          <% # If user is signed %>
          <% if signed_in? %>
            
            <% # Link to index page %>
            <li><%= link_to "Users", users_path %></li>

            <% # Create a dropdown box %>
            <li id="fat-menu" class="dropdown">
              
              <% # Link that tobbles the box up and down with text Account %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              
              <% # Dropdown box container %>
              <ul class="dropdown-menu">
                
                <% # Link to the profile page with action to current_user %>
                <li><%= link_to "Profile", current_user %></li>
                
                <% # Link to the Settings page with stub action %>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                
                <% # Divider to seterate following link from rest of drop box %>
                <li class="divider"></li>
                <li>
                  
                  <% 
                    # Link to let user signout with action signout_path
                    # and a method of delete.
                  %>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>

          <% # If the user is not signed in %>
          <% else %>

            <% 
              # Create a link to allow user to sign in 
              # with action signin_path. 
            %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>    
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- 
	Shim for legacy Internet Explorers that a earlier than
	version 9
-->
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	    <% # Helper class full_title is called %>
	    <% # sending variable title as a parameter. %>
	    
	    <% # Variable title is declared in main page %>
	    <% # being rendered through the layout page. %>
	    <title>
	      <%= full_title(yield(:title)) %>
	    </title>
	  	<%= stylesheet_link_tag    "application", 
	  		:media => "all" %>
	  	<%= javascript_include_tag "application" %>
	  	<%= csrf_meta_tags %>

      <% 
        # Renders content of layouts/_shim.htm.erb
        # into the place of the page.
      %>
	    <%= render 'layouts/shim' %>
	</head>
<body>
  <%
    # Renders the header here from
    # layouts/_header.html.erb to this
    # location of the page.
  %>
  <%= render 'layouts/header' %>
  <!-- Main body of the page -->
  <div class="container">

    <% 
       # Cycle through each item in flash and assign the key and value
       # pair into block variable.
    %>
    <% flash.each do |key, value| %>
      <%
        # Create a div tag that contains the value of the 
        # value key pair.
      %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>

    <% # Renders the main html file here. %>
    <%= yield %>
    <%
    # Render the footer from layouts/_footer.html.erb
    # to this location of page
    %>
    <%= render 'layouts/footer' %>

    <%
      # Displays a hash that contains the controller
      # and action for the page. It is only displayed
      # if rails is in a development environment.
    %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>